name: flutterforge
description: A powerful Flutter CLI tool for creating projects with interactive prompts, supporting Clean Architecture, BLoC, Freezed, Go Router, and internationalization.
version: 1.10.25
homepage: https://github.com/victorsdd01/flutter_forge
repository: https://github.com/victorsdd01/flutter_forge.git
issue_tracker: https://github.com/victorsdd01/flutter_forge/issues

environment:
  sdk: '>=3.7.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  path: ^1.9.1
  http: ^1.2.0
  interact: ^2.2.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3

# Export the main library
flutterforge_cli:
  main: lib/flutterforge_cli.dart

# Executable configuration
executables:
  flutterforge: flutterforge


